server:
  port: 4000
spring:
  application:
    name: member-manager

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
  instance:
    prefer-ip-address: true



##解决错误 com.netflix.client.ClientException: Load balancer does not have available server for client:panfeng-item-service
##开启eureka负载均衡策略
#ribbon:
#  eureka:
#    enabled: true